### ISSUE TITLE
Unable to use on heroku

### ISSUE THREAD

**Issue by markcerv** [sztamas/django-iprestrict-redux#4]
Hello,

I tried to use django-iprestrict-redux as an INSTALLED_APP ("iprestrict") on django 3.1.3 running on python 3.7.9 and EVERY page gives me a 403 error for every page that I try to view.  When I look at the logs, here's what I see:

```
Nov 07 16:31:15 beverly-hills-90210 heroku/router at=info method=GET path="/admin/" host=www.REDACTED.com request_id=f82fdec3-118a-4e98-ae42-85affe019621 fwd="52.11.12.20" dyno=web.1 connect=1ms service=969ms status=403 bytes=369 protocol=https
Nov 07 16:31:15 beverly-hills-90210 app/web.1 WARNING:iprestrict.middleware:Client IP 52.11.12.20 forwarded by untrusted proxy 10.159.227.245
Nov 07 16:31:15 beverly-hills-90210 app/web.1 WARNING:django.request:Forbidden (Permission denied): /admin/
Nov 07 16:31:15 beverly-hills-90210 app/web.1 Traceback (most recent call last):
Nov 07 16:31:15 beverly-hills-90210 app/web.1   File "/app/.heroku/python/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
Nov 07 16:31:15 beverly-hills-90210 app/web.1     response = get_response(request)
Nov 07 16:31:15 beverly-hills-90210 app/web.1   File "/app/.heroku/python/lib/python3.7/site-packages/sentry_sdk/integrations/django/middleware.py", line 134, in __call__
Nov 07 16:31:15 beverly-hills-90210 app/web.1     return f(*args, **kwargs)
Nov 07 16:31:15 beverly-hills-90210 app/web.1   File "/app/.heroku/python/lib/python3.7/site-packages/sentry_sdk/integrations/django/middleware.py", line 90, in sentry_wrapped_method
Nov 07 16:31:15 beverly-hills-90210 app/web.1     return old_method(*args, **kwargs)
Nov 07 16:31:15 beverly-hills-90210 app/web.1   File "/app/.heroku/python/lib/python3.7/site-packages/iprestrict/middleware.py", line 34, in __call__
Nov 07 16:31:15 beverly-hills-90210 app/web.1     client_ip = self.extract_client_ip(request)
Nov 07 16:31:15 beverly-hills-90210 app/web.1   File "/app/.heroku/python/lib/python3.7/site-packages/iprestrict/middleware.py", line 50, in extract_client_ip
Nov 07 16:31:15 beverly-hills-90210 app/web.1     client_ip = self.extract_client_ip_proxied_request(client_ip, forwarded_for)
Nov 07 16:31:15 beverly-hills-90210 app/web.1   File "/app/.heroku/python/lib/python3.7/site-packages/iprestrict/middleware.py", line 66, in extract_client_ip_proxied_request
Nov 07 16:31:15 beverly-hills-90210 app/web.1     raise exceptions.PermissionDenied
Nov 07 16:31:15 beverly-hills-90210 app/web.1 django.core.exceptions.PermissionDenied
Nov 07 16:31:15 beverly-hills-90210 app/web.1 10.159.227.245 - - [07/Nov/2020:14:31:15 -1000] "GET /admin/ HTTP/1.1" 403 135 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36"
```

In my settings.base.py I have
```

...

INSTALLED_APPS = [
    # 3rd party heroku app - says it should be first
    "scout_apm.django",
    # 'django.contrib.admin',
    "django.contrib.admin.apps.SimpleAdminConfig",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    #
    # third-party apps
    #
    "adminplus",
    "django_celery_beat",
    "django_celery_results",
    "django_extensions",
    "tinymce",  # pip install django-tinymce
    "rest_framework",
    "tastypie",  # django-tastypie
    "iprestrict",  # django-iprestrict-redux
    #
    # local apps for this program
    #
    "myapp",
]


MIDDLEWARE = [
    # Django security middleware should already be the first thing on the list.
    # Never load any middleware before Django security.
    "django.middleware.security.SecurityMiddleware",
    # "iprestrict.middleware.IPRestrictMiddleware",
    # Added for heroku and static files
    # 'whitenoise.middleware.WhiteNoiseMiddleware',
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "rollbar.contrib.django.middleware.RollbarNotifierMiddleware",
]

IPRESTRICT_GEOIP_ENABLED = False
```

And in my urls.py, I have:

```

urlpatterns = [
    re_path(r"^iprestrict/", include("iprestrict.urls", namespace="iprestrict")),
    path("admin/", admin.site.urls),
    path("", include("myapp.urls")),
    path("tinymce/", include("tinymce.urls")),
]

```

Any ideas?

**Comment by sztamas** [comment]
Hi,

The problem you encounter is because `django-iprestrict-redux` doesn't trust any proxies by default.
With apps deployed on Heroku, when the load balancer IP is dynamic, your best current option is probably to set `IPRESTRICT_TRUST_ALL_PROXIES` to `True` in your settings.

Thanks,
Tamas

**Comment by markcerv** [comment]
Tamas,

Thank you!  That worked!  
And thank you for forking the original iprestrict into this redux version and keeping it going.  Such a useful APP.

Mark

**Comment by sztamas** [comment]
No worries, I'm happy it helps!

All the best,

Tamas
